### ISSUE TITLE
updated wiki on ipa320/ROSRagnarEDU

### ISSUE THREAD

**Issue by ipa-mirb** [Blueworkforce/ROSRagnarEDU#14]
Dear all, @shisha101 took the time to write notes/howtos as a companion wiki to the github repo forked from ROSRagnarEDU and hosted at ipa320. Since it is not possible to submit pull requests for wiki changes, can you take the initiative on your side to pull in these changes to the wiki? so that we possilby keep a single knowledge base, together with the fablabs and the other development/deployment sites. Thanks!

Direct instructions courtesy of @shisha101: Create a directory and:

`git clone https://github.com/Blueworkforce/ROSRagnarEDU.wiki.git`

`git pull https://github.com/ipa320/ROSRagnarEDU.wiki.git`

`git push`

@mf-bwf 
@Jmeyer1292

**Comment by Jmeyer1292** [comment]
@ipa-mirb Thanks to you and @shisha101 for your assistance on this. I'll get on this this week before the consortium meeting.

**Comment by mf-bwf** [comment]
Thanks for your assistance, I have merged the ROSRagnarEDU wiki.
I expect to have someone at Blueworkforce expand on the wiki in the coming weeks.

**Comment by shisha101** [comment]
As discussed [here](https://github.com/shisha101/ROSRagnarEDU/issues/8), this repo. (Blueworkforce/ROSRagnarEDU) will be used as the main repo for code consolidation and development.
